server:
  port: 8083

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:h2:mem:hoteldb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
