server:
  port: 8084

spring:
  application:
    name: location-service
  datasource:
    url: jdbc:h2:mem:locationdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
