server:
  port: 8082

spring:
  application:
    name: vols-service
  datasource:
    url: jdbc:h2:mem:voldb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
